### ISSUE TITLE
Per page/section table of content (TOC)

### ISSUE THREAD

**Issue by bpj** [json-schema-org/understanding-json-schema#106]
It would be nice to have a local table of contents on each page on the web site.  Now, if you aren't sure which subsection you are looking for you have to scroll down the page looking out for headings, and it is very easy to miss headings that way. If there were a TOC (list (with sublists) with links) it would be much easier to see what is found on the page.

**Comment by Relequestual** [comment]
Great idea. Pull Request welcome.

**Comment by mdboom** [comment]
Closed as #107 is merged.
