### ISSUE TITLE
JSON Schema Reference should be more prominent

### ISSUE THREAD

**Issue by Bartvds** [json-schema-org/understanding-json-schema#11]
I think the reference page should be more prominently linked (it is way more usable then the original specs).

This one: http://spacetelescope.github.io/understanding-json-schema/reference/index.html

Also this 5 bullets link menu could be on top of every reference child page I think, because you'd usually navigate this intensively when building a schema.

I'd send a PR but I'm not setup to get hacking to run the Makefile (Windows)

**Comment by gregglind** [comment]
+1 on this as well.  Google brings up this tutorial before the keyword reference, before the keyword reference :)

**Comment by mdboom** [comment]
This is now addressed in master.
