### ISSUE TITLE
Since we already have a new 2019-09 draft, would it be the case to create a draft-07 branch in this repository? Or right before adding info specific to 2019-09?

### ISSUE THREAD

**Issue by idgserpro** [json-schema-org/understanding-json-schema#114]
Right now, we have this note in the documentation:

> Note: This book describes JSON Schema draft 7. Earlier versions of JSON Schema are not completely compatible with the format described here, but for the most part, those differences are noted in the text.

One day, "Understanding json schema" will have support for **2019-09** specification. Since a lot of people will be using older drafts that still need to have reference to older documentation, it would be nice to have a branch or a tag of this repository while in draft 7 for reference. If you don't want the overhead of doing this right now, please consider adding this right before adding docs about the new **2019-09** draft.

**Comment by Relequestual** [comment]
Ideally, we'd love to move to docusaurus or something similar, but it's a matter of finding time.
Currently, I want to try and make sure people are focused on the test suite, THEN we can come back and focus here and the main website.

I agree with your concerns though.

**Comment by mdboom** [comment]
Personally, I prefer a single document that covers all of the drafts from 4 on.  It is currently written for draft 7, with differences pointed out, and I think this is much more useful for seeing the differences between drafts than diffing multiple versions of the docs.  See the Python stdlib documentation for another good (IMHO) example of this approach.

**Comment by benjagm** [comment]
With the release of the new JSON Schema website this issue is going to be closed as not planed.
