### ISSUE TITLE
Draft 2019-09: Use correct $schema URI

### ISSUE THREAD

**Issue by about-code** [json-schema-org/understanding-json-schema#134]
The [guide](https://github.com/json-schema-org/understanding-json-schema/blob/master/source/reference/schema.rst#advanced) contains examples with `$schema: "http://json-schema.org/draft/2019-09/schema#"` to refer to JSON-Schema 2019-09 whereas the spec uses `$schema: "https://json-schema.org/draft/2019-09/schema"`.

Confirmed via https://github.com/json-schema-org/json-schema-spec/issues/988.

**Comment by jdesrosiers** [comment]
Fixed by #158. The draft 2019-09 identifier was removed because the site doesn't cover that draft yet. However, updates are in progress and it will be added back in (the right way) relatively soon.
