### ISSUE TITLE
wrong use of allof instead of anyof? 

### ISSUE THREAD

**Issue by Aymonz** [json-schema-org/understanding-json-schema#137]
in the multiple countries example in 
https://json-schema.org/understanding-json-schema/reference/conditionals.html

**Comment by Relequestual** [comment]
No, that's correct.

If it were `anyOf`, if country was `United States of America`, the second and third subschemas in the `anyOf` array would still be valid when the postcode was invalid.

`allOf` makes sure all subschemas are applied.

I'm going to close this issue with this comment, but I'm happy to continue and discuss.
