### ISSUE TITLE
Migrate from Travis CI to GitHub Actions for build process

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#163]
Our builds and deploys have stopped working because Travis CI .org is no longer working.
We could migrate to the new .com version, but might as well use GitHub Actions.

**Comment by MikeRalphson** [comment]
[This](https://github.com/json-schema-org/understanding-json-schema/blob/master/.travis.yml) doesn't look too frightening. [Here](https://github.com/APIs-guru/APIs-guru.github.io/blob/main/.github/workflows/deploy.yaml) is a relatively simple build/test/deploy workflow for comparison.

**Comment by derberg** [comment]
> Travis CI .org is no longer working.

oh, damn, had no idea

**Comment by jdesrosiers** [comment]
It's not as trivial as it looks, but I think the biggest hurdle was already cleared when setting up a docker container with all the build dependencies for local development. I think we'll need a custom action, but it looks like it's relatively easy to build an action that just runs the build in a docker container.
