### ISSUE TITLE
Fix netlify build previews

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#182]
It looks like after Netlify updated their build-image from 4.4 to 4.5, the build preview is broken.

Last successful deploy preview: https://app.netlify.com/sites/lucid-bardeen-10edfb/deploys/618977f53d31ad0008c6d102
First failed deploy preview: https://app.netlify.com/sites/lucid-bardeen-10edfb/deploys/61a14281b8ff390007646a62

Line 3 identifies the build image tag.
On inspection of the [changelog](https://github.com/netlify/build-image/blob/focal/CHANGELOG.md), I can't see what would have caused this issue.

I found one other person experiencing a similar issue on the Netlify support forums: https://answers.netlify.com/t/issues-with-netlify-python-requests/48018
The only [lead](https://www.claudiokuenzler.com/blog/1114/urllib3-or-chardet-doesnt-match-a-supported-version-check-esxi-hardware) seemed to be related to an Ubunto OS update, which isn't covered by the build-image minor version jump.

@jdesrosiers had a go at trying to fix the build, but had no luck: https://github.com/json-schema-org/understanding-json-schema/pull/181

Related: https://github.com/json-schema-org/understanding-json-schema/issues/165

**Comment by Relequestual** [comment]
Having battled with this for a while, I'm out of ideas.
I managed to duplicate the issue locally using [Netlify's image-build](https://github.com/netlify/build-image#running-locally).
Most of the [advice I see](https://stackoverflow.com/questions/50202238/python-pip-requestsdependencywarning-urllib3-1-9-1-or-chardet-2-3-0-doe) says uninstall `requests` and reinstall it, but I don't see how we can do that.
It seems like the issue is `urllib3` and `chardet` are being picked up from the system installed versions.

**Comment by Relequestual** [comment]
@jdesrosiers I re-ran the deploy previews, and we seem to have hit a different error.
I tried to make sense of it, but I can't, and I don't know if it's just becasue I don't know this side of things or I'm just run down and exhausted.

**Comment by jdesrosiers** [comment]
@Relequestual The error seems to be because python 3.8 is being used which isn't compatible with the code in the repo. Is it possible to tell netlify to use python 3.7?

**Comment by jdesrosiers** [comment]
Actually, it looks like we are using 3.8 for the local builds (which is working), so not sure why netlify is having issues.

**Comment by jdesrosiers** [comment]
Fixed in https://github.com/json-schema-org/understanding-json-schema/pull/181
I twas shown to be working in https://github.com/json-schema-org/understanding-json-schema/pull/183

I updated a couple things and that seems to have made Netlify happy. It's still not clear what changed to make the changes necessary, but hopefully it will stay fixed for a while.

**Comment by Relequestual** [comment]
Thanks for digging into this @jdesrosiers! 🙇‍♂️
