### ISSUE TITLE
Tuple validation, required elements in tuple

### ISSUE THREAD

**Issue by bali182** [json-schema-org/understanding-json-schema#190]
https://json-schema.org/understanding-json-schema/reference/array.html#tuple-validation

The example for tuple validation demonstrates it using this sample:

```json
{
  "type": "array",
  "prefixItems": [
    { "type": "number" },
    { "type": "string" },
    { "enum": ["Street", "Avenue", "Boulevard"] },
    { "enum": ["NW", "NE", "SW", "SE"] }
  ]
}
```
And then says the following input is valid:

```json
[10, "Downing", "Street"]
```
Since I don't see any distinguishing factor between the last schema item (`{ "enum": ["NW", "NE", "SW", "SE"] }`) and the rest, does this mean all the following are valid?

```json
[1, "str"]
```
```json
[1]
```
```json
[]
```

If so how would I express a schema identical to this, except it **MUST** havel all 4 items, meaning neither of them is optional?

**Comment by Relequestual** [comment]
You are correct.
You must use minItems: http://json-schema.org/understanding-json-schema/reference/array.html#length

**Comment by bali182** [comment]
Understood, thanks!
