### ISSUE TITLE
condition and allOf

### ISSUE THREAD

**Issue by DMGlion** [json-schema-org/understanding-json-schema#204]
I am trying to add an 'AND' condition for rule but it doesn't seems to be rendering. 
I am using Angular, look's like allOf is not supported in Angular, I am correct on that? If I am correct what I can use alternatively?

```
{
              "type": "Control",
              "label": "Element",
              "scope": "#/properties/element/scp",
              "rule": {
                "effect": "DISABLE",
                "condition": {
                  "allOf": [
                    {
                      "scope": "#/properties/element/secext",
                      "schema": { "const": false }
                    },
                    {
                      "scope": "#/properties/element/cpif",
                      "schema": { "const": false }
                    }
                  ]
                }
               }
}
```

**Comment by jdesrosiers** [comment]
Sorry, we don't have answers to questions about specific implementations here. This repo is only for the Understanding JSON Schema site and covers the JSON Schema specification in general, not any particular implementation. I'd point you to the right place the ask your question if I knew where that was.
