### ISSUE TITLE
Archive the repo

### ISSUE THREAD

**Issue by Julian** [json-schema-org/understanding-json-schema#212]
If I understand https://github.com/json-schema-org/website/issues/84#issuecomment-1744571011 this repo is no longer used, right? (As in it doesn't have anything to do with what's on the site now?)

If so seems like we should archive it to avoid confusion and/or PRs.

**Comment by Relequestual** [comment]
See https://github.com/json-schema-org/website/issues/53#issuecomment-1742742329
(There are required steps before archiving)
