### ISSUE TITLE
What is JSON Hyper Schema, and how is it different from the regular JSON Schema?

### ISSUE THREAD

**Issue by Ajedi32** [json-schema-org/understanding-json-schema#28]
This site was very helpful in explaining JSON Schema, but one topic which didn't seem to be covered at all was JSON Hyper Schema. What exactly is that, and how is it different from the regular JSON Schema? From what I've read so far, I'm guessing it has something to do with links between schema documents?

**Comment by mdboom** [comment]
This is definitely something that would be worthwhile to add.  I haven't actually ever used or had a need for it myself.  This may be fairly low priority for me, as it's a little far afield from my day-to-day work needs.  I'll self-assign this if I find the time to work on it, otherwise @Ajedi32 or anyone else reading along should feel free to submit a patch, which I'd be more than grateful to receive.

**Comment by handrews** [comment]
@Ajedi32 @mdboom We are approaching publication of draft-07 of Hyper-Schema, which in my completely biased opinion will be the first draft that is really fully functional with clear implementation requirements.  I am hoping to add a conformance test suite as well.

I would be interested in contributing something about Hyper-Schema here, either directly or by referring back to guide material on json-schema.org itself that I plan to write.  But as many people know of this resource, it would be great to have some Hyper-Schema guidance here.

**Comment by mdboom** [comment]
@handrews: As I'm trying to pull this out of deep freeze, your contribution in this regard is of course still welcome.  Let's be in touch and self-assign this if either one of us finds the time to write this up.

**Comment by handrews** [comment]
@mdboom sounds good- I am actively working on a major addition to Hyper-Schema for draft-08, so we should probably just go straight to that draft.  More on this very soon.

**Comment by benjagm** [comment]
With the release of the new JSON Schema website this issue is going to be closed. However let's continue the discussion in: https://github.com/json-schema-org/website/issues/156
