### ISSUE TITLE
PHP examples?

### ISSUE THREAD

**Issue by Potherca** [json-schema-org/understanding-json-schema#48]
Would there be any interest in having PHP code equivalents added?

I wouldn't mind adding those if there is interested in accepting such a PR...

**Comment by embray** [comment]
Sure--would gladly accept PRs for other language-specific docs!

**Comment by mdboom** [comment]
Closing due to the closing of #55, but @Potherca, if you're still interested after all these years, I'd be happy to help you push this over the finish line.
