### ISSUE TITLE
Move this repo to outside spacetelescope repo?

### ISSUE THREAD

**Issue by SaOgaz** [json-schema-org/understanding-json-schema#68]
Hey @mdboom, we we're discussing this repo in a meeting, and it came up that it might be more appropriate (given it's common external usage) to move this repo outside the spacetelescope organization.  STScI has no plan to maintain it going forward. Do you want to take it? If not, any ideas  of who would?

Same could be said for the https://github.com/spacetelescope/yaml-schema-standard repo.

**Comment by Relequestual** [comment]
Hi there. The JSON Schema team has much appreciated this resource! If Mozilla wanted to take it over, that would be great as long as redirects are set up. It would also be a great opportunity to collaborate with those who have some form of investment in the spec and can drive changes moving forward.

Equally, it may be something we could move within the JSON Schema org repo, and give full repo access to you @mdboom or anyone else who wants to / can work on it officially.

If I don't pick up any replies here in a timly manner, please come join the JSON Schema slack.

**Comment by mdboom** [comment]
Sorry, just seeing this now.  I do think it would make sense to move this under the JSON Schema org, if that's still a possibility, @Relequestual.

**Comment by pllim** [comment]
Please let us know if anyone needs special permission to make this happen. Thank you!

**Comment by Relequestual** [comment]
OK.
I think we (JSON Schema) will need to decide what we should do here.
We've just had a big update to our site which inclues a new "learn" section.

I'll flag this for discussion!

**Comment by Relequestual** [comment]
Feel free to assing myself to this task so I can better keep track that my action is required on this. Thanks.

**Comment by mdboom** [comment]
Thanks.  Unfortunately, I can't assign you since this project is now STScI folks-only.  However, I'm happy to coordinate with you to move this if that's still something the json schema org wants to do.  If not, just let me know, and I'll just move it to my personal Github account.

FWIW, I've spent some time updating this for Draft 6 on my personal fork, and will add Draft 7 once Python's jsonschema library adds support so it can be validated.  I'm eager to push that out to wherever the next location of this is likely to be.

**Comment by pllim** [comment]
@Relequestual , please accept collaborator invite, then I should be able to assign you. @mdboom , you should still have admin access to this repo, but if that is not the case, I'll be happy to fix the settings for you, so just let me know. Thank you, all!

**Comment by mdboom** [comment]
So, these are (I think) the discrete steps:

- [ ] Transfer this repo to json-schema org ([see this](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/))
- [ ] Give @mdboom commit rights there, along with anyone else interested in having them
- [ ] Make sure github pages is set up correctly in new repo, and serving at https://json-schema.github.io/understanding-json-schema
- [ ] Set up redirects in the spacetelescope repo to the new repo
- [ ] Optionally, redirect a subdomain of json-schema.org to https://json-schema.github.io/understanding-json-schema
- [ ] Start merging in @mdboom's recent changes for modernizing the build chain, updating for new drafts, etc.

**Comment by Relequestual** [comment]
@pllim Thanks for the invite. I've noted it, but have not yet been able to action it. Will do shortly.
@mdboom This is all really exciting!
I think a few of these things are out of the order they should be.

I'm going to reach out to github support first, as transfering the repo to a different org WILL effect the live site as it runs on github.io. I think we might actually not need to set up any redirects, but this is something I'll check with Github. They are usually pretty speedy to respond.

I'll be back here once I know more.
I'm on this!

**Comment by mdboom** [comment]
Cool, thanks for drilling down on those details!

**Comment by Relequestual** [comment]
Update:

When transfering a repo from one org to another, all github.com URLs will redirect as expected, but github.io aka github pages will NOT redirect.

After the transfer, you COULD create a new repo her with the same name, and add a readme with a redirect notice, and have the github pages site auto redirect, but then the github.com URLs would not redirect.

Any thoughts on how best to proceed anyone?

**Comment by mdboom** [comment]
I think the redirecting the Github pages, with a README note is probably our best option.  Most users of the content will be automatically redirected, and potential contributors (a much smaller and more motivated group) will just have the small hiccup of needing to jump over to the new repo.  We can update the "Fork my on Github" banner and any other contributing instructions like that to the new repo as well.

It does seem like we'll need to coordinate this move carefully so minimize downtime at the old URLs, however.  Maybe we'll want to set aside some time when myself, someone at STScI and someone on the json-schema org are all available at the same time (which will be a little tricky with timezones)...

**Comment by pllim** [comment]
I'll be happy to help next week. Please email me to coordinate.

**Comment by Relequestual** [comment]
I'm in UK, so coordination is possible.
@mdboom Would you like to put together a revised ordered checklist based on these plans? =]

@pllim Sorry, I do not have your email! Maybe @mdboom can provide?

**Comment by pllim** [comment]
@Relequestual , please check your email. :smile:

**Comment by mdboom** [comment]
So, these are (I think) the discrete steps:

- [ ] Transfer this repo to json-schema org ([see this](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/))
- [ ] Make sure github pages is set up correctly in new repo, and serving at https://json-schema.github.iounderstanding-json-schema
- [ ] Create new repo here (spacetelescope/understanding-json-schema), and set up redirects to new repo
- [ ] Give @mdboom commit rights to new repo, along with anyone else interested in having them
- [ ] Optionally, redirect a subdomain of json-schema.org to https://json-schema.github.io/understanding-json-schema
- [ ] Start merging in @mdboom's recent changes for modernizing the build chain, updating for new drafts, etc.

**Comment by mdboom** [comment]
Information on setting up the redirects:

https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

**Comment by pllim** [comment]
> commit rights to new repo, along with anyone else interested in having them

@drdavella might be interested.

**Comment by drdavella** [comment]
I'm open to it, but since I haven't contributed anything thus far, I'm also happy to just submit PRs like everyone else if necessary.

**Comment by Relequestual** [comment]
OK. Just thought about one snag on this, but it's practically a non issue.
Can't do json-schema.github.io/something on a different repo, as far as I know.
SHOULD be able to do something like understanding.json-schema.github.io though.

Do you think that sounds OK?
Once we have control of the domain back, we could do understanding.json-schema.org! =]

**Comment by mdboom** [comment]
@Relequestual: I'm not sure I follow.  If we put the new repo at `json-schema/understanding-json-schema`, it should serve at `json-schema.github.io/understanding-json-schema`.  I don't think github lets you do two levels of subdomains like `understanding.json-schema.github.io`, at least I've never come across it.

It should be possible to ultimately set up `understanding.json-schema-org` pointing to wherever, though, which is a pretty cool domain, I agree!

**Comment by SaOgaz** [comment]
I'm gonna hold off on merging any of the other PR's people have made.  Is that good with everyone? i.e. https://github.com/spacetelescope/understanding-json-schema/pull/70#issuecomment-400033103

**Comment by pllim** [comment]
I think we can close this now? :tada:

**Comment by mdboom** [comment]
Yep.  This is complete.

**Comment by pllim** [comment]
Thanks again, @mdboom and @Relequestual !
