### ISSUE TITLE
examples / reference about conditional relationships towards field values

### ISSUE THREAD

**Issue by machinaeXphilip** [json-schema-org/understanding-json-schema#76]
i found [https://stackoverflow.com/a/38781027/2602592]( https://stackoverflow.com/a/38781027/2602592) extremely helpful as a reference for understanding the different approaches to schemas depending on field values. 

it covers dependencies, anyOf (Implication) and if-then-else

Would be a wonderful addition, though in the answer spans till v7.

**Comment by Relequestual** [comment]
There are plans to do a lot of work on this resource to include new examples and patterns. Thanks for raising these specific issues.

**Comment by sdshq** [comment]
A question about the if-then-else syntax, how to elegantly describe this: "property 'bar' may exist in an instance, ONLY if the property 'foo' has value 'x' "?
