### ISSUE TITLE
Update for Draft 7

### ISSUE THREAD

**Issue by mdboom** [json-schema-org/understanding-json-schema#79]
Once support for Draft 7 is in Julian/jsonschema, work can start on this in earnest.

**Comment by mdboom** [comment]
Note to self: Include #74 in this work.

**Comment by Julian** [comment]
Still some kinks to work out (please lemme know if you find any!) but just pushed out a first draft 7 alpha release (v3.0.0a3).

**Comment by jdesrosiers** [comment]
This has been done for some time.
