### ISSUE TITLE
Include simple example of `"additionalProperties": false`

### ISSUE THREAD

**Issue by Relequestual** [json-schema-org/understanding-json-schema#87]
The new learning section looks great! Super props to @retrosight!

One common question is around additional properties not defined in the properties schema still passing validation.
I think we've been pretty clear that key words ADD constraints, but I still expect this is sometimes missed.

I feel a small section at the end of the getting started section could address the use case for `"additionalProperties": false` and show the simplest of examples.

I think sometimes we (including myself) forget that reading RFCs is hard. =]

**Comment by Relequestual** [comment]
*uses github beta* Issue transferred!

**Comment by jdesrosiers** [comment]
This seems to be sufficiently covered including the common difficulties with combining schemas with `"additionalProperties": false`.
