### ISSUE TITLE
Allow "null" as value for numbers or the like

### ISSUE THREAD

**Issue by MarHai** [json-schema-org/understanding-json-schema#95]
Hi there,

thanks for the great work--please keep it up :)

I was wondering whether you've thought about providing an option to allow null values for other types. I'm thinking about something like this (pseudo code):

```
{
  "type": "number",
  "minimum": 0,
  "nullAllowed": true
}
```

This would then validate true against the following examples, whereas currently the second example would fail:

- `{ "foo": 13 }`
- `{ "foo": null }`

Thanks,
Mario

**Comment by handrews** [comment]
@MarHai you probably meant to file this on the json-schema-spec repo (this repo is for the documentation project).

The spec already allows this with the following syntax:

```JSON
{
  "type": ["number", "null"],
  "minimum": 0
}
```

The only major project known to not support this syntax is OpenAPI, and we are working with them on this issue.  They are exploring two different ways to support the syntax in 3.1.
